title: Lisa Nguyen
logo: /assets/headshot.jpg
description: Passionate about exploring Consumer Behavior Analysis, Product Development & eCommerce Strategy
[Linkedin](https://www.linkedin.com/in/lisapwin/)
[Contact](Lisa.ngu71@gmail.com)
show_downloads: true
theme: jekyll-theme-minimal
