title: Lisa Nguyen
logo: /assets/headshot.jpg
description: Passionate about exploring Consumer Behavior Analysis, Product Development & eCommerce Strategy
show_downloads: true
theme: jekyll-theme-minimal
