title: Lisa Nguyen
logo: /assets/prof_headshot.png
description: Aspiring Product Analyst looking to explore opportunities in Product Development, Consumer Behavior & Digital Strategy
show_downloads: true
theme: jekyll-theme-minimal
