title: Lisa Nguyen
logo: /assets/Untitled design.png
description: Passionate about exploring Consumer Behavior Analysis, Product Development & E-commerce Strategy
show_downloads: true
theme: jekyll-theme-minimal
