title: Lisa Nguyen
#logo: /assets
description: Aspiring Analyst with a passion for leveraging data & technology to discover insights for informed decision-making and impactful solutions.
#show_downloads: true
theme: jekyll-theme-minimal
